version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."
    TF_VERSION: "1.3.7"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"
      - "mv terraform /bin"
      - "rm terraform.zip"
  build:
    commands:
      - "cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}"
      - "echo ## TERRAFORM APPLY : Starting with the Terraform Apply"
      - "terraform apply -input=false tfapply"

artifacts:
  files:
    - '**/*'